"""The persisted status vocabularies.

These strings are written to Postgres and read back by Python, by SQL functions,
and by the dashboard's JavaScript. **None of them can be renamed** — a rename
orphans every existing row. This module exists to stop them being *retyped*:
before it, `audits.status` was spelled out at nine sites across three languages,
`measurement_status` at four, and `autopilot_paused_reason` at five, with
nothing to notice when a copy drifted.

`app/apply_outcome.py` proved the pattern for one fragment (its enum values are
pinned to the persisted strings by a test). This generalises it.

Values are plain `str` class attributes rather than `Enum` members so they can
be passed straight to postgrest filters and compared to raw DB values without
`.value` at every call site.

Two mirrors live outside Python and cannot import this module:

  * `supabase/migrations/20260730010000_next_audit_candidate_exclude_measurement.sql`
    re-types the picker's skip lists in SQL.
  * `app/static/status.js` maps audit statuses to pills.

`tests/test_status_vocab.py` parses both and fails if either drifts.
"""
from __future__ import annotations


class AuditStatus:
    """`audits.status` — the lifecycle of one audit row."""

    PENDING = "pending"
    APPLIED = "applied"
    FAILED = "failed"
    QUARANTINED = "quarantined"
    #: YouTube refused the title edit because the video is in a Test & Compare
    #: experiment. Distinct from FAILED: it is retryable once the test ends.
    BLOCKED_TEST_AND_COMPARE = "blocked_test_and_compare"
    #: Generated by a reflection candidate prompt, never applied.
    SHADOW_PENDING = "shadow_pending"
    REVERTED = "reverted"
    APPROVED = "approved"
    REJECTED = "rejected"


ALL_AUDIT_STATUSES = frozenset({
    AuditStatus.PENDING, AuditStatus.APPLIED, AuditStatus.FAILED,
    AuditStatus.QUARANTINED, AuditStatus.BLOCKED_TEST_AND_COMPARE,
    AuditStatus.SHADOW_PENDING, AuditStatus.REVERTED,
    AuditStatus.APPROVED, AuditStatus.REJECTED,
})

#: A video whose LATEST audit is in one of these is not re-audited. Only
#: `failed` (and never-audited) qualify for a retry. Mirrored in SQL by
#: next_audit_candidate().
AUDIT_PICKER_SKIP_STATUSES = frozenset({
    AuditStatus.APPLIED, AuditStatus.PENDING, AuditStatus.QUARANTINED,
    AuditStatus.BLOCKED_TEST_AND_COMPARE, AuditStatus.SHADOW_PENDING,
})


class MeasurementStatus:
    """`audits.measurement_status` — Loop 1's per-audit lifecycle."""

    #: Never measured: measurement was off, the window could not be built, or
    #: the pre-change window was dormant. NOT a verdict — carries no evidence.
    NOT_APPLICABLE = "not_applicable"
    AWAITING_WINDOW = "awaiting_window"
    MEASURING = "measuring"
    WIN = "win"
    NEUTRAL = "neutral"
    REGRESSION = "regression"


#: In-flight: re-auditing these videos would confound an open experiment.
#: Mirrored in SQL by next_audit_candidate(). Tuple, not frozenset — call sites
#: pass it to postgrest `.in_()`, which needs an ordered sequence.
ACTIVE_MEASUREMENT_STATUSES = (
    MeasurementStatus.AWAITING_WINDOW,
    MeasurementStatus.MEASURING,
)

#: Terminal verdicts that count as evidence. Excludes NOT_APPLICABLE.
MEASURED_STATUSES = (
    MeasurementStatus.WIN,
    MeasurementStatus.NEUTRAL,
    MeasurementStatus.REGRESSION,
)


class OutcomeDecision:
    """`audits.outcome_decision` — what was done about a verdict."""

    NONE = "none"
    KEPT = "kept"
    REVERTED = "reverted"
    #: Reserved by the Loop-1 redo spec; nothing writes it yet
    #: (docs/PHASE_2_TRACK2_LOOP1_REDO.md).
    REDO_QUEUED = "redo_queued"


class PausedReason:
    """`channels.autopilot_paused_reason`."""

    TOKEN_EXPIRED = "token_expired"
    REPEATED_FAILURES = "repeated_failures"
    UNSAFE_MODEL = "unsafe_model"


#: Pauses autopilot clears by itself once the cause can no longer apply.
#: token_expired needs re-consent and unsafe_model needs a config change, so
#: neither self-expires.
AUTO_EXPIRE_PAUSE_REASONS = (PausedReason.REPEATED_FAILURES,)


class PromptVersionStatus:
    """`prompt_versions.status` — reflection's champion/challenger states."""

    SHADOW = "shadow"
    LIVE = "live"
    RETIRED = "retired"
    RETIRED_REGRESSION = "retired_regression"


class ReflectionMode:
    """`audit_configs.reflection_mode` — how a candidate prompt is handled.

    Overlaps PromptVersionStatus in two of its members but is a different
    column with different meaning: this is a per-channel *policy*, that is a
    per-version *state*.
    """

    SHADOW = "shadow"
    LIVE = "live"
    AUTO = "auto"


#: Modes that promote a new candidate immediately.
PROMOTING_REFLECTION_MODES = (ReflectionMode.LIVE, ReflectionMode.AUTO)
