"""The persisted status vocabularies.

These strings are written to Postgres and read back by Python, by SQL functions,
and by the dashboard's JavaScript. **None of them can be renamed** — a rename
orphans every existing row. This module exists to stop them being *retyped*:
before it, `audits.status` was spelled out at nine sites across three languages,
`measurement_status` at four, and `autopilot_paused_reason` at five, with
nothing to notice when a copy drifted.

`app/apply_outcome.py` proved the pattern for one fragment (its enum values are
pinned to the persisted strings by a test). This generalises it.

Values are plain `str` class attributes rather than `Enum` members so they can
be passed straight to postgrest filters and compared to raw DB values without
`.value` at every call site.

Three mirrors live outside Python and cannot import this module:

  * `supabase/migrations/20260730010000_next_audit_candidate_exclude_measurement.sql`
    re-types the picker's skip lists in SQL.
  * `app/static/status.js` maps audit statuses to pills.
  * `supabase/migrations/20261006020000_interventions.sql` re-types
    ACTIVE_INTERVENTION_STATUSES in its one-active-Midas-intervention index.

`tests/test_status_vocab.py` parses all three and fails if either drifts.
"""
from __future__ import annotations


class AuditStatus:
    """`audits.status` — the lifecycle of one audit row."""

    PENDING = "pending"
    APPLIED = "applied"
    FAILED = "failed"
    QUARANTINED = "quarantined"
    #: YouTube refused the title edit because the video is in a Test & Compare
    #: experiment. Distinct from FAILED: it is retryable once the test ends.
    BLOCKED_TEST_AND_COMPARE = "blocked_test_and_compare"
    #: Generated by a reflection candidate prompt, never applied.
    SHADOW_PENDING = "shadow_pending"
    REVERTED = "reverted"
    APPROVED = "approved"
    REJECTED = "rejected"


ALL_AUDIT_STATUSES = frozenset({
    AuditStatus.PENDING, AuditStatus.APPLIED, AuditStatus.FAILED,
    AuditStatus.QUARANTINED, AuditStatus.BLOCKED_TEST_AND_COMPARE,
    AuditStatus.SHADOW_PENDING, AuditStatus.REVERTED,
    AuditStatus.APPROVED, AuditStatus.REJECTED,
})

#: A video whose LATEST audit is in one of these is not re-audited. Only
#: `failed` (and never-audited) qualify for a retry. Mirrored in SQL by
#: next_audit_candidate().
AUDIT_PICKER_SKIP_STATUSES = frozenset({
    AuditStatus.APPLIED, AuditStatus.PENDING, AuditStatus.QUARANTINED,
    AuditStatus.BLOCKED_TEST_AND_COMPARE, AuditStatus.SHADOW_PENDING,
})


class MeasurementStatus:
    """`audits.measurement_status` — Loop 1's per-audit lifecycle."""

    #: Never measured: measurement was off, the window could not be built, or
    #: the pre-change window was dormant. NOT a verdict — carries no evidence.
    NOT_APPLICABLE = "not_applicable"
    AWAITING_WINDOW = "awaiting_window"
    MEASURING = "measuring"
    WIN = "win"
    NEUTRAL = "neutral"
    REGRESSION = "regression"


#: In-flight: re-auditing these videos would confound an open experiment.
#: Mirrored in SQL by next_audit_candidate(). Tuple, not frozenset — call sites
#: pass it to postgrest `.in_()`, which needs an ordered sequence.
ACTIVE_MEASUREMENT_STATUSES = (
    MeasurementStatus.AWAITING_WINDOW,
    MeasurementStatus.MEASURING,
)

#: Terminal verdicts that count as evidence. Excludes NOT_APPLICABLE.
MEASURED_STATUSES = (
    MeasurementStatus.WIN,
    MeasurementStatus.NEUTRAL,
    MeasurementStatus.REGRESSION,
)


class OutcomeDecision:
    """`audits.outcome_decision` — what was done about a verdict."""

    NONE = "none"
    KEPT = "kept"
    REVERTED = "reverted"
    #: Reserved by the Loop-1 redo spec; nothing writes it yet
    #: (the redo design draft, docs/PHASE_2_TRACK2_LOOP1_REDO.md, was deleted 2026-10-06; see git history).
    REDO_QUEUED = "redo_queued"


class PausedReason:
    """`channels.autopilot_paused_reason`."""

    TOKEN_EXPIRED = "token_expired"
    REPEATED_FAILURES = "repeated_failures"
    UNSAFE_MODEL = "unsafe_model"


#: Pauses autopilot clears by itself once the cause can no longer apply.
#: token_expired needs re-consent and unsafe_model needs a config change, so
#: neither self-expires.
AUTO_EXPIRE_PAUSE_REASONS = (PausedReason.REPEATED_FAILURES,)


class PromptVersionStatus:
    """`prompt_versions.status` — reflection's champion/challenger states."""

    SHADOW = "shadow"
    LIVE = "live"
    RETIRED = "retired"
    RETIRED_REGRESSION = "retired_regression"


class ReflectionMode:
    """`audit_configs.reflection_mode` — how a candidate prompt is handled.

    Overlaps PromptVersionStatus in two of its members but is a different
    column with different meaning: this is a per-channel *policy*, that is a
    per-version *state*.
    """

    SHADOW = "shadow"
    LIVE = "live"
    AUTO = "auto"


#: Modes that promote a new candidate immediately.
PROMOTING_REFLECTION_MODES = (ReflectionMode.LIVE, ReflectionMode.AUTO)


class InterventionLever:
    """`interventions.lever` — which routing or title lever a row records."""

    BACKLINKS = "backlinks"
    PLAYLIST = "playlist"
    SHORT_LINK = "short_link"
    TITLE = "title"


ALL_INTERVENTION_LEVERS = frozenset({
    InterventionLever.BACKLINKS, InterventionLever.PLAYLIST,
    InterventionLever.SHORT_LINK, InterventionLever.TITLE,
})


class InterventionOrigin:
    """`interventions.origin` — who made the change."""

    MIDAS = "midas"
    #: An SEO-team edit Midas detected on sync (B3). Never has a holdout arm.
    HUMAN = "human"


ALL_INTERVENTION_ORIGINS = frozenset({InterventionOrigin.MIDAS, InterventionOrigin.HUMAN})


class InterventionArm:
    """`interventions.arm` — the control-group split (spec Part 2 §1.3)."""

    TREATED = "treated"
    #: Chosen for the lever by triage, recorded, and deliberately NOT applied.
    HOLDOUT = "holdout"
    #: Human edits and declined triages: not part of a treated/holdout split.
    NOT_APPLICABLE = "n/a"


ALL_INTERVENTION_ARMS = frozenset({
    InterventionArm.TREATED, InterventionArm.HOLDOUT, InterventionArm.NOT_APPLICABLE,
})


class InterventionStatus:
    """`interventions.status` — the lifecycle of one intervention row.

    Shares `applied` and `measuring` with AuditStatus / MeasurementStatus by
    spelling only; this is a different column on a different table.
    """

    PLANNED = "planned"
    APPLIED = "applied"
    MEASURING = "measuring"
    JUDGED = "judged"
    CANCELLED = "cancelled"
    #: Triage said `no_change` (spec Part 2 §2.2). Nothing was changed.
    DECLINED = "declined"
    #: The holdout arm's in-window state: recorded, not applied, measured.
    HOLDOUT = "holdout"
    #: The window was extended once and the indicator floor still wasn't
    #: reached (spec Part 2 §1.7). Excluded from the week's learning.
    INSUFFICIENT_DATA = "insufficient_data"


ALL_INTERVENTION_STATUSES = frozenset({
    InterventionStatus.PLANNED, InterventionStatus.APPLIED,
    InterventionStatus.MEASURING, InterventionStatus.JUDGED,
    InterventionStatus.CANCELLED, InterventionStatus.DECLINED,
    InterventionStatus.HOLDOUT, InterventionStatus.INSUFFICIENT_DATA,
})

#: An intervention in one of these is open: the video is inside a measurement
#: window (or about to be), so a second Midas change would confound it (spec
#: Part 2 §1.6). Holdout counts — changing a held-out video contaminates the
#: control arm. `declined` doesn't: nothing was changed. Mirrored in SQL by the
#: partial unique index interventions_one_active_midas_per_video.
ACTIVE_INTERVENTION_STATUSES = frozenset({
    InterventionStatus.PLANNED, InterventionStatus.APPLIED,
    InterventionStatus.MEASURING, InterventionStatus.HOLDOUT,
})
